language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
# command to run tests
script: py.test
